### ISSUE TITLE
Can't enable the driver

### ISSUE THREAD

**Issue by eqwalker** [linode/docker-volume-linode#14]
docker plugin enable linode/docker-volume-linode
Error response from daemon: dial unix /run/docker/plugins/dbc67ba543ec1cac789bbaaa9ad1b8d33664e95b7345277265e4fc3cc86a011e/linode-driver.sock: connect: no such file or directory

**Comment by displague** [comment]
Did you attempt this using [docker-machine-driver-linode](https://github.com/linode/docker-machine-driver-linode)?  I was able to reproduce this error by attempting to enable the plugin remotely using the docker-machine settings.

When I logged into the docker-machine, however,

```
# Run from my MacBookPro
$ docker-machine ssh docker-13567
```
```
# .. following commands run from the Linode
# $ docker plugin upgrade linode/docker-volume-linode
# Error response from daemon: plugin linode/docker-volume-linode:latest already exists
```

```
$ docker plugin upgrade linode/docker-volume-linode
Upgrading plugin linode/docker-volume-linode:latest from linode/docker-volume-linode:latest to linode/docker-volume-linode:latest
Plugin "docker.io/linode/docker-volume-linode:latest" is requesting the following privileges:
 - network: [host]
 - mount: [/dev]
 - allow-all-devices: [true]
 - capabilities: [CAP_SYS_ADMIN]
Do you grant the above permissions? [y/N] y
latest: Pulling from linode/docker-volume-linode
13f5f2771dcd: Download complete
Digest: sha256:750ab1a32b69de8ebc6d5eb7e7d20a8706823cd8c862b83d1300add477f4b029
Status: Downloaded newer image for linode/docker-volume-linode:latest
Upgraded plugin linode/docker-volume-linode:latest to docker.io/linode/docker-volume-linode:latest
```

**Comment by displague** [comment]
Actually, `plugin upgrade` seems to bypass the error messages, but puts the plugin in a state where the volume mounts are using the local filesystem instead of the Linode volume.

I'm able to reproduce this issue, so I'm digging in.  Thanks.

**Comment by eqwalker** [comment]
Great thank you!

**Comment by ricardorg79** [comment]
The plugin should be working as expected if configured and enabled.
The error has to do with the state when installed.  I will submit a patch to account for it and avoid the error message.

Can you confirm that it works if you configure it and enable it?  even if you see the message when installing it?

Thank you.

**Comment by ricardorg79** [comment]
Never mind... I'm looking into the issue.
