### ISSUE TITLE
 Must provide a region or a Linode ID

### ISSUE THREAD

**Issue by andyg5000** [linode/docker-volume-linode#24]
I'm unable to get a volume created and get the following error 

`Error response from daemon: create my-test-volume: VolumeDriver.Create: Create(my-test-volume) Failed: [400] Must provide a region or a Linode ID`

I followed all the steps of the README including setting the linode-region and linode-label on the plugin. 

Any thoughts what I'm doing wrong? 

I also tried to specify `--opt region=us-southeast`, `--opt linode-region=us-southeast`, and `--opt linode.region=us-southeast` to the docker volume create command with no luck. 

Thanks!

**Comment by displague** [comment]
Hi @andyg5000 

The plugin should be configured with the region option, as described here:

https://github.com/linode/docker-volume-linode#changing-the-plugin-configuration
* `docker plugin set linode linode-region=<linode region>`
* the `linode-region` option should only be necessary if the `linode-label` is not provided.  
* `linode-label` is not necessary if the system hostname matches the Linode label.

I don't believe this option is available at "volume create" time.

Additionally, and most importantly, the `us-southeast` region **does not** have the Block Storage Volume service. Here is a [community post about the regional availability of the block storage service](https://www.linode.com/community/questions/344/when-will-block-storage-be-available-in-my-datacenter).  Toronto (`ca-east`) will also have the service.

The README.md of this project shows that `us-southeast` is a viable region for this plugin.  I'll update that list and leave a note and link to the community post.

**Comment by andyg5000** [comment]
Hey @displague 

Not sure what I'm doing wrong, but still getting the same error with us-east. Here are my steps to test this plugin out.

apk update
apk upgrade
apk add docker
service docker start
docker plugin install --alias linode linode/docker-volume-linode
docker plugin disable linode
docker plugin set linode linode-token=XXXXX
docker plugin set linode linode-region=us-east
docker plugin enable linode
docker volume create -o size=10 -d linode my-test-volume-10

This ends in: 

`Error response from daemon: create my-test-volume-10: VolumeDriver.Create: Create(my-test-volume-10) Failed: [400] Must provide a region or a Linode ID`

Thanks for the support!

**Comment by displague** [comment]
I'm wondering if the region option isn't working.  Can you try specifying the `linode-label` option or set the system hostname to match the Linode label before enabling the plugin:

https://wiki.alpinelinux.org/wiki/Configure_Networking

**Comment by andyg5000** [comment]
Unfortunately neither update you suggested solved my problem. The weird thing is that I don't see the error or " Linode ID" in the source code of this plugin

**Comment by displague** [comment]
Give the v0.14 line a shot.  The docker image has been updated, be sure to pull.

https://hub.docker.com/r/linode/docker-volume-linode/tags

Region is no longer required and `linode-label` is inferred from the system hostname.

If your hostname does not match the linode-label, make sure when using the `linode-label` option that you are specifying the label ("linode1234" or the name you specified "foo") and not the linode id ("1234").

**Comment by zliang-akamai** [comment]
This should has been resolved.
